### ISSUE TITLE
Add the ability to log interrupted periods.

### ISSUE THREAD

**Issue by Fertion** [eatgrass/obsidian-pomodoro-timer#1]
For example, only 16 minutes out of 25 have passed, when the counter is reset, those 16 minutes are logged.
Unfinished pomodoro are marked differently so that they can be counted

**Comment by eatgrass** [comment]
Hi! I understand that logging requirements can vary, so I am considering implementing a more generic approach, such as a log template. What do you think?

**Comment by Fertion** [comment]
Hi. Yeah, that sounds great.

**Comment by eatgrass** [comment]
@Fertion I've just released an update, and I believe this template script wil cover the case you mentioned. Modify it as necessary. 

Please ensure that the [Templater](https://github.com/SilentVoid13/Templater) plugin is installed, as this script relies on it.

```javascript
<%* 
if (log.mode == "WORK") {
  if (!log.finished) {
    tR = `🟡 Focused ${log.duration} / ${log.session} minutes`;
  } else {
    tR = `🍅 Focused ${log.duration} minutes`;
  }
} else {
  tR = `☕️ Took a break from ${log.begin.format("HH:mm")} to ${log.end.format(
    "HH:mm"
  )}`;
} 
%>
```

Here are some references that might be helpful:

[Readme - Custom log template](https://github.com/eatgrass/obsidian-pomodoro-timer/blob/master/README.md#custom-log-template-optional)
[Templater - Documentation](https://silentvoid13.github.io/Templater/)

**Comment by Fertion** [comment]
Just what I need, thanks.
This works if you press button 1, but does not work if you press button 2 with the timer running.
![image](https://github.com/eatgrass/obsidian-pomodoro-timer/assets/102726751/7a4efa9e-ed91-4d07-bfed-1cbb7f249bdf)

**Comment by eatgrass** [comment]
That was intentional actually.
I plan to disable the `mode switching` while the timer is running to avoid any mix-ups and keep the timer from getting reset by mistake.

**Comment by debMan** [comment]
When I click reset, the current log is missed and not added to my logs. Is it normal or intentional?
