### ISSUE TITLE
Finishing the work before time stops

### ISSUE THREAD

**Issue by juuHuu** [eatgrass/obsidian-pomodoro-timer#10]
Thank you for such a useful plugin! This function greatly enhances the efficiency of my work!
Sometimes I have finished my work before the time stops, and I want to log the time I have spent. However, pause or reset the timer won't create any log. Is there any way to automatically create a log when I manually stop the timer?

**Comment by eatgrass** [comment]
Please check out the [Custom Log Template](https://github.com/eatgrass/obsidian-pomodoro-timer?tab=readme-ov-file#custom-log-template-optional)

It includes an example of how to log unfinished sessions, if you reset a running timer, it'll output something like `🟡 Focused 10 / 25 minutes.`. you can modify this template to fit your needs

**Comment by juuHuu** [comment]
Thank you so much! Custom log Template function solve the problem.
But I met a problem when setting the log template, which I'll record here hoping could help others: when choose Custom as log format, a log template input box appears. Instead of create a template file and input the file path in this input box, the template code should  be directly input into the box!

**Comment by eatgrass** [comment]
I should have made it clearer. I'll update the document. Thank you for bringing it to my attention.
