### ISSUE TITLE
failed to load/install plugin

### ISSUE THREAD

**Issue by imshenwei** [eatgrass/obsidian-pomodoro-timer#13]
system: win 10
obsidian version: v1.5.3
pomodoro-timer-version: only tested with v1.0.8/v1.07

# situation
1. "failed to load plugin" (while downloaded and extracted from github)
2. "failed to install plugin"(while install from obsidian store)

**Comment by eatgrass** [comment]
Could you try that again? It might be related to the new release's draft status, which seems to disrupt the plugin store. Please let me know if it works this time.

**Comment by imshenwei** [comment]
it works right now.
