### ISSUE TITLE
[Feature Request] Labelling or Describing Pomodoro work

### ISSUE THREAD

**Issue by benjaminwestern** [eatgrass/obsidian-pomodoro-timer#14]
Hey @eatgrass,

Thank you for creating the almost 'perfect' plugin for my time tracking woes. I would love to see the ability to add a 'task name' or 'description' to a Pomodoro work session or even the ability to change the fact it says 'work' 

The idea being that I can better describe what the block is being used for. Leading to reporting on those blocks becoming easier in future.

Just an idea, currently getting around this by using your data view task example. 

Thanks again for the excellent addition to my toolkit

b

**Comment by eatgrass** [comment]
Hi @benjaminwestern, thank you for sharing your ideas. 
Could you let me know which version you're currently using? I've just released a new update today, it includes a task field in the log, this feature is still relatively simple but sets a foundation for future enhancements to track time and tasks more effectively. 
I've taken note of your requirements, as soon as I have a clearer idea of implementation, I'll start working on them.

**Comment by eatgrass** [comment]
yeah, the editable task description is reasonable for sure, and I'll investigate the bug tomorrow. Thank you once again.

**Comment by eatgrass** [comment]
fixed 1.1.1

**Comment by eatgrass** [comment]
Hi @benjaminwestern 
I've added task tracking in the new update, which should cover most of the cases we mentioned here. I'd be glad to hear any more feedback you have.

**Comment by benjaminwestern** [comment]
Thank you sir, I will keep enjoying your plugin and let you know :) thanks again!
b
