### ISSUE TITLE
Enable/disable sound notification setting

### ISSUE THREAD

**Issue by vaygr** [eatgrass/obsidian-pomodoro-timer#2]
It would be great to have a slider to turn on/off sound notifications. And also to choose a custom sound to play.

**Comment by eatgrass** [comment]
yeah, please upgrade to the latest release
https://github.com/eatgrass/obsidian-pomodoro-timer/releases/tag/1.0.6

**Comment by vaygr** [comment]
Excellent, thanks a lot!

What if turning off notification sound would also hide custom sound setting?

**Comment by eatgrass** [comment]
Hi @vaygr 

> What if turning off notification sound would also hide custom sound setting?

If you turn off the notification sound, it simply mutes all notifications. no matter if you've got a custom sound set up or not.

**Comment by vaygr** [comment]
Yeah, I understand. That's just to make settings page look neater. Similar to what happens to logging when you set it to `None`.

**Comment by eatgrass** [comment]
Thanks, that's a good suggestion, will do it in the next release
