### ISSUE TITLE
Without selecting a task, it is not recorded in the active file.

### ISSUE THREAD

**Issue by theotheo** [eatgrass/obsidian-pomodoro-timer#23]
Hello. Thank you for developing the plugin. It's interesting to see what features you are adding—it makes me reflect on my own tracking practices. And special thanks for considering my request about tracking in the active file.

However, it seems that since version 1.1.2, I can't record the log directly in the active file. It works if a task in this file is selected. But if no task is selected, a log entry will appear in the daily file. I can't figure out if I'm doing something wrong or if this is intended behavior.

I'll be glad for your advice

**Comment by eatgrass** [comment]
Hey @theotheo, I apologize for the breaking change that was introduced in the recent update, which shifted the tracking context from file-based to task-based. This change is why you now need to select a specific task to log into the active file. 
I am looking for a way to address the situation where no task is selected, and I'll let you know as soon as I get a solution

**Comment by theotheo** [comment]
I could work on a fix if it's convenient.

**Comment by eatgrass** [comment]
Sure, that would be great!
