### ISSUE TITLE
Cant log sessions after the update

### ISSUE THREAD

**Issue by natarslan** [eatgrass/obsidian-pomodoro-timer#27]
Hello,

Thank you for this amazing plugin. 

I use the plugin together with tasks. It had been working just fine until today. After the update, I can run the timer but cant see any of my logs in the log file. I tried different things like:
- restart obsidian
- removing the current task, ran timer, logging failed.
- added text to the last line in the log file, ran timer, logging failed.
- toogled "prefer saving to task file" option, tested with both on/off version, logging failed.
- toogled "enable task tracking" option,  tested with both on/off version, logging failed.

Once the timer is done I get a pop-up message: "Folder already exists".
I cant see any messages in the developer tools.

Am I missing something obvious?

**Comment by eatgrass** [comment]
Hi， @natarslan 
I'll look into it soon, have you tried changing the log file path

**Comment by eatgrass** [comment]
wow, egregious error, thank you for reporting!

**Comment by eatgrass** [comment]
Sorry for the inconvenience caused by the bug. I have launched a new release. Please let me know if the issue is resolved.

**Comment by natarslan** [comment]
Wow! Super quick fix. I can confirm that its working now.
