### ISSUE TITLE
Choose the reset type

### ISSUE THREAD

**Issue by Freddd13** [eatgrass/obsidian-pomodoro-timer#37]
Thank you for developing the awesome plugin!

Sometimes I want to adjust the work/break time. I found the timer is always reset to the start of the current state when I press the reset button. That is, when the timer is running for "work", it will return to the start of the work state. However, it seems the min time duration in the settings is limited to 1 minute, which means I have to wait for at least 1minute to start from another state. I think it's kind of inconvenient. Would you mind making the reset state switchable? Thank you very much.

**Comment by eatgrass** [comment]
Hi, you can click the break/work text on the timer to switch the session after reset
