### ISSUE TITLE
Distinguish between work/break time in the status bar

### ISSUE THREAD

**Issue by vaygr** [eatgrass/obsidian-pomodoro-timer#4]
Right now it's unclear what timer is running in the status bar.

Another Obsidian plugin uses an emoji for that. But I think that's not super-clean and timer icon looks better. Maybe using light green color for the timer icon would be a good option?

**Comment by eatgrass** [comment]
I'd like to make the display less distracting. Perhaps I could just append the 'mode' after the time, or add a tooltip on hover?

**Comment by vaygr** [comment]
Agreed, I think tooltip would be best then.
