### ISSUE TITLE
Sharing a template

### ISSUE THREAD

**Issue by iczrac** [eatgrass/obsidian-pomodoro-timer#44]
Thanks @eatgrass for this awesome plugin！

I am sharing this template for someone who may need it.

`<%*
if (log.mode == "WORK") {
  if (!log.finished) {
    if (log.task.blockLink == "") {
        tR = `- 🟡 (pomodoro::Focused) (duration:: ${log.duration}m) (begin:: ${log.begin.format("YYYY-MM-DD HH:mm")}) - (end:: ${log.end.format("YYYY-MM-DD HH:mm")}) Focus on:[[${log.task.fileName.slice(0, -3)}]]`;
    } else {
        tR = `- 🟡 (pomodoro::Focused) (duration:: ${log.duration}m) (begin:: ${log.begin.format("YYYY-MM-DD HH:mm")}) - (end:: ${log.end.format("YYYY-MM-DD HH:mm")}) Focus on:[[${log.task.fileName.slice(0, -3)}#^${log.task.blockLink.slice(2)}|${log.task.name}]]`;
    }
  } else {
    if (log.task.blockLink == "") {
        tR =  `- 🍅 (pomodoro::WORK) (duration:: ${log.duration}m) (begin:: ${log.begin.format("YYYY-MM-DD HH:mm")}) - (end:: ${log.end.format("YYYY-MM-DD HH:mm")}) Work on:[[${log.task.fileName.slice(0, -3)}]]`;
    } else {
        tR =  `- 🍅 (pomodoro::WORK) (duration:: ${log.duration}m) (begin:: ${log.begin.format("YYYY-MM-DD HH:mm")}) - (end:: ${log.end.format("YYYY-MM-DD HH:mm")}) Work on:[[${log.task.fileName.slice(0, -3)}#^${log.task.blockLink.slice(2)}|${log.task.name}]]`;
    }
  }
} else {
    if (log.task.blockLink == "") {
        tR =  `- 🥤 (pomodoro::BREAK) (duration:: ${log.duration}m) (begin:: ${log.begin.format("YYYY-MM-DD HH:mm")}) - (end:: ${log.end.format("YYYY-MM-DD HH:mm")}) Break for:[[${log.task.fileName.slice(0, -3)}]]`;
    } else {
        tR =  `- 🥤 (pomodoro::BREAK) (duration:: ${log.duration}m) (begin:: ${log.begin.format("YYYY-MM-DD HH:mm")}) - (end:: ${log.end.format("YYYY-MM-DD HH:mm")}) Break for:[[${log.task.fileName.slice(0, -3)}#^${log.task.blockLink.slice(2)}|${log.task.name}]]`;
    }
}
%>`

**Comment by eatgrass** [comment]
Sorry for the late reply, I've been quite busy recently. I really appreciate you sharing your custom script. It's great to see that this plugin can be of help to you! 👍
