### ISSUE TITLE
Custom notification sound doesn't work

### ISSUE THREAD

**Issue by Gentleman03** [eatgrass/obsidian-pomodoro-timer#9]
Hello, I have tried to set custom notification sound but it doesn't seem to work. I tried to place the file in obsidian vault, outside, in plugin root folder, in plugins folder, on another disc etc and nothing has worked. Am I doing something work or is there an issue with this option?

Tested on most recent obsidian and plugin version.

BTW. Love your plugin :)

**Comment by eatgrass** [comment]
Hi, @Gentleman03 

Quick steps for you:

1. Place your audio file in your vault.
2. Set its path from the vault's root. Say your file's in `AudioFiles` and named `notification.mp3`, your path would be `AudioFiles/notification.mp3`. Don't forget the file extension (like `.mp3`, `.wav` etc.).

Also, I created an example vault. It might help you get things up and running: [example.zip](https://github.com/eatgrass/obsidian-pomodoro-timer/files/13796925/example.zip). 

Let me know if you can get it working

**Comment by eatgrass** [comment]
Hi @Gentleman03 

Sorry about the bug, I've fixed it in the new release and updated the doc about the [custom notification setting](https://github.com/eatgrass/obsidian-pomodoro-timer?tab=readme-ov-file#custom-notification-sound)

**Comment by Gentleman03** [comment]
Thank you, now it's working :)
